### ISSUE TITLE
metadata not working on SummarizedExperiment

### ISSUE THREAD

**Issue by samWieczorek** [rformassspectrometry/QFeatures#114] opened 2020-09-17 13:48 UTC
Hi Laurent,
I have a strange behaviour within RStudio about the metadata function. Sometimes, it works well either on QFeatures objects or SummarizedExperiment objects. And sometimes, It seems that R cannot find the right metadata function for SE objects 

```
> Error in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function ‘metadata’ for signature ‘"SummarizedExperiment"’
> 
```

And when I try to load a QFeatures object, sometimes this error appears

```
> data(hlpsms)
> hl <- readQFeatures(hlpsms, ecol = 1:10, name = "psms")
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘metadata<-’ for signature ‘"DFrame"’
```

Maybe something is going wrong in my environnment but I cannot find what happens.
Do you have an idea ?

Best regards

Sam

**Comment by lgatto** [comment] 2020-09-17 14:25
You might need to update your packages. What does you `sessionInfo()` say?

**Comment by samWieczorek** [comment] 2020-09-17 14:29
```
sessionInfo() 
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
 [1] compiler  parallel  stats4    stats     graphics  grDevices utils     datasets  methods  
[10] base     

other attached packages:
 [1] QFeatures_0.99.3            MultiAssayExperiment_1.14.0 SummarizedExperiment_1.18.2
 [4] DelayedArray_0.14.1         matrixStats_0.56.0          Biobase_2.48.0             
 [7] GenomicRanges_1.40.0        GenomeInfoDb_1.24.2         IRanges_2.22.2             
[10] S4Vectors_0.26.1            BiocGenerics_0.34.0         shiny_1.5.0                
[13] Prostar2_2.0.1              testthat_2.3.2             

loaded via a namespace (and not attached):
  [1] highcharter_0.8.2       vioplot_0.3.5           tidyr_1.1.2            
  [4] missForest_1.4          ggplot2_3.3.2           bit64_4.0.5            
  [7] knitr_1.29              data.table_1.13.0       RCurl_1.98-1.2         
 [10] AnnotationFilter_1.12.0 doParallel_1.0.15       generics_0.0.2         
 [13] preprocessCore_1.50.0   callr_3.4.4             cowplot_1.1.0          
 [16] usethis_1.6.1           RSQLite_2.2.0           mice_3.11.0            
 [19] europepmc_0.4           bit_4.0.4               enrichplot_1.8.1       
 [22] rlist_0.4.6.1           xml2_1.3.2              lubridate_1.7.9        
 [25] httpuv_1.5.4            assertthat_0.2.1        viridis_0.5.1          
 [28] xfun_0.17               hms_0.5.3               promises_1.1.1         
 [31] fansi_0.4.1             progress_1.2.2          readxl_1.3.1           
 [34] caTools_1.18.0          dendextend_1.14.0       igraph_1.2.5           
 [37] DBI_1.1.0               quantmod_0.4.17         htmlwidgets_1.5.1      
 [40] purrr_0.3.4             ellipsis_0.3.1          crosstalk_1.1.0.1      
 [43] dplyr_1.0.2             backports_1.1.10        FactoMineR_2.3         
 [46] markdown_1.1            geepack_1.3-1           vctrs_0.3.4            
 [49] remotes_2.2.0           here_0.1                TTR_0.24.2             
 [52] withr_2.2.0             ggforce_0.3.2           triebeard_0.3.0        
 [55] itertools_0.1-3         xts_0.12.1              prettyunits_1.1.1      
 [58] cluster_2.1.0           DOSE_3.14.0             lazyeval_0.2.2         
 [61] crayon_1.3.4            pkgconfig_2.0.3         tweenr_1.0.1           
 [64] nlme_3.1-149            pkgload_1.1.0           ProtGenerics_1.20.0    
 [67] rlang_0.4.7             miniUI_0.1.1.1          lifecycle_0.2.0        
 [70] colourpicker_1.1.0      downloader_0.4          affyio_1.58.0          
 [73] tcltk_4.0.2             cellranger_1.1.0        randomForest_4.6-14    
 [76] rprojroot_1.3-2         polyclip_1.10-0         graph_1.66.0           
 [79] Matrix_1.2-18           urltools_1.7.3          boot_1.3-25            
 [82] zoo_1.8-8               ggridges_0.5.2          processx_3.4.4         
 [85] viridisLite_0.3.0       mzR_2.22.0              bitops_1.0-6           
 [88] visNetwork_2.0.9        KernSmooth_2.23-17      blob_1.2.1             
 [91] geeM_0.10.1             stringr_1.4.0           qvalue_2.20.0          
 [94] gridGraphics_0.5-0      scales_1.1.1            leaps_3.1              
 [97] memoise_1.1.0           magrittr_1.5            plyr_1.8.6             
[100] gplots_3.0.4            gdata_2.18.0            zlibbioc_1.34.0        
[103] cp4p_0.3.6              DAPARdata2_2.2          scatterpie_0.1.5       
[106] factoextra_1.0.7        RColorBrewer_1.1-2      lme4_1.1-23            
[109] pcaMethods_1.80.0       cli_2.0.2               affy_1.66.0            
[112] XVector_0.28.0          DAPARdata_1.18.0        ps_1.3.4               
[115] MASS_7.3-53             tidyselect_1.1.0        vsn_3.56.0             
[118] stringi_1.5.3           shinyBS_0.61            yaml_2.2.1             
[121] GOSemSim_2.14.2         dockerfiler_0.1.3       norm_1.0-9.5           
[124] MALDIquant_1.19.3       ggrepel_0.8.2           grid_4.0.2             
[127] sass_0.2.0              fastmatch_1.1-0         tools_4.0.2            
[130] imp4p_1.0               rstudioapi_0.11         MsCoreUtils_1.1.2      
[133] foreach_1.5.0           gridExtra_2.3           scatterplot3d_0.3-41   
[136] farver_2.0.3            mzID_1.26.0             ggraph_2.0.3           
[139] DAPAR2_2.4              digest_0.6.25           rvcheck_0.1.8          
[142] BiocManager_1.30.10     ggformula_0.9.4         Iso_0.0-18.1           
[145] Rcpp_1.0.5              broom_0.7.0             MESS_0.5.7             
[148] later_1.1.0.1           shinyWidgets_0.5.3      ncdf4_1.17             
[151] httr_1.4.2              MSnbase_2.14.2          AnnotationDbi_1.50.3   
[154] rhandsontable_0.3.7     ggstance_0.3.4          colorspace_1.4-1       
[157] XML_3.99-0.5            fs_1.5.0                truncnorm_1.0-8        
[160] splines_4.0.2           sm_2.2-5.6              statmod_1.4.34         
[163] graphlayouts_0.7.0      multtest_2.44.0         ggplotify_0.0.5        
[166] shinyalert_2.0.0        xtable_1.8-4            nloptr_1.2.2.2         
[169] jsonlite_1.7.1          tidygraph_1.2.0         flashClust_1.01-2      
[172] R6_2.4.1                pillar_1.4.6            htmltools_0.5.0        
[175] mime_0.9                minqa_1.2.4             glue_1.4.2             
[178] fastmap_1.0.1           clusterProfiler_3.16.1  DT_0.15                
[181] BiocParallel_1.22.0     missMDA_1.17            codetools_0.2-16       
[184] fgsea_1.14.0            mvtnorm_1.1-1           pkgbuild_1.1.0         
[187] lattice_0.20-41         tibble_3.0.3            curl_4.3               
[190] gtools_3.8.2            attempt_0.3.1           config_0.3             
[193] zip_2.1.1               openxlsx_4.1.5          GO.db_3.11.4           
[196] golem_0.2.1             shinyjs_2.0.0           survival_3.2-3         
[199] limma_3.44.3            roxygen2_7.1.1          desc_1.2.0             
[202] munsell_0.5.0           DO.db_2.9               GenomeInfoDbData_1.2.3 
[205] iterators_1.0.12        impute_1.62.0           reshape2_1.4.4         
[208] mosaicCore_0.8.0        gtable_0.3.0           
```

**Comment by lgatto** [comment] 2020-09-17 23:36
This is weird indeed. All your packages look up-to-date, but I am unable to reproduce the error, all works fine on my side.

What does the following say?

```r
BiocManager::valid()
```

**Comment by lgatto** [comment] 2020-09-29 17:30
Closing for now - feel free to reopen if necessary.

**Closed as completed by lgatto** 2020-09-29 17:30 UTC
